### ISSUE TITLE
Not working well in dark mode

### ISSUE THREAD

**Issue by ghmatu** [popbones/Dictionary.EnglishCollocation#1]
Character is not seen in dark mode.
In dark mode, background of the main page of Dictionary.app is white and character is also white. 
Would you have a chance to open the way to reproduce the file so that I can try ?

**Comment by popbones** [comment]
I haven't touched this for year. I'm not sure I can still find the script that did the transformation. But I loaded the dictionary on my current system (macOS 10.15.3), it seems working fine under dark theme. What kind of issue do you have with Dark theme?

If you still have issue, you can tweak `DefaultStyle.css` inside since that's the only file controlling the styling.

**Comment by ghmatu** [comment]
My MacOS version is 10.14.6(Mojave). Attached is what it looks like in my
environment. As you can see,  almost all the texts(excpet for "links") are
not visible.
[image: 001.png]

When I turned dark mode off, it looked like as below.
[image: 002.png]

But I got a hint to tweak DefaultStyle.css. I will try to tweak the file.

Regards,
Takaaki

2020年2月29日(土) 23:01 popbones <notifications@github.com>:
